import type { FloorPlan } from '@/types/designer';

function uid(prefix: string, i: number) { return `${prefix}${i}`; }

type PlanTemplate = Omit<FloorPlan, 'id' | 'createdAt' | 'updatedAt'>;

export const PLAN_TEMPLATES: { name: string; description: string; icon: string; plan: PlanTemplate }[] = [
  {
    name: 'Studija',
    description: '35 m² · 1 kambarys',
    icon: '🏢',
    plan: {
      name: 'Studija',
      wallHeight: 2.6,
      rooms: [
        { id: 'r1', name: 'Kambarys/Virtuvė', type: 'living', x: 0, y: 0, width: 6, height: 5, floorMaterial: 'wood', wallMaterial: 'white', wallColor: '#f8f8f8', floorColor: '#c8a26b' },
        { id: 'r2', name: 'Vonios kambarys', type: 'bathroom', x: 0, y: 5, width: 2.5, height: 2, floorMaterial: 'tile', wallMaterial: 'white', wallColor: '#f8f8f8', floorColor: '#e0e0e0' },
        { id: 'r3', name: 'Prieškambaris', type: 'hallway', x: 2.5, y: 5, width: 3.5, height: 2, floorMaterial: 'tile', wallMaterial: 'cream', wallColor: '#f5f0e0', floorColor: '#d0c8b0' },
      ],
      doors: [
        { id: 'd1', roomId: 'r1', wall: 'bottom', position: 0.6, width: 0.9, swingIn: true },
        { id: 'd2', roomId: 'r2', wall: 'right', position: 0.3, width: 0.7, swingIn: true },
      ],
      windows: [
        { id: 'w1', roomId: 'r1', wall: 'top', position: 0.25, width: 1.4, height: 1.2, sillHeight: 0.9 },
        { id: 'w2', roomId: 'r1', wall: 'top', position: 0.65, width: 1.4, height: 1.2, sillHeight: 0.9 },
        { id: 'w3', roomId: 'r1', wall: 'right', position: 0.5, width: 1.2, height: 1.2, sillHeight: 0.9 },
      ],
      furniture: [
        { id: 'f1', type: 'single-bed', name: 'Lova', x: 0.2, y: 0.2, width: 1.0, depth: 2.0, rotation: 0, color: '#e8dcc8' },
        { id: 'f2', type: 'sofa', name: 'Sofa', x: 2.5, y: 2.5, width: 2.2, depth: 0.9, rotation: 180, color: '#7f9ab5' },
        { id: 'f3', type: 'coffee-table', name: 'Kavos staliukas', x: 2.8, y: 1.6, width: 1.0, depth: 0.5, rotation: 0, color: '#c8a26b' },
        { id: 'f4', type: 'kitchen-counter', name: 'Virtuvinė spintelė', x: 4.5, y: 0.1, width: 1.4, depth: 0.6, rotation: 0, color: '#e8e8e8' },
        { id: 'f5', type: 'toilet', name: 'Tualetas', x: 0.1, y: 5.1, width: 0.5, depth: 0.7, rotation: 0, color: '#f0f0f0' },
        { id: 'f6', type: 'sink', name: 'Kriauklė', x: 1.5, y: 5.1, width: 0.6, depth: 0.5, rotation: 0, color: '#e0e0e0' },
      ],
    },
  },
  {
    name: '1 miegamojo butas',
    description: '55 m² · 4 kambariai',
    icon: '🏠',
    plan: {
      name: '1 miegamojo butas',
      wallHeight: 2.7,
      rooms: [
        { id: 'r1', name: 'Svetainė', type: 'living', x: 0, y: 0, width: 5.5, height: 4, floorMaterial: 'wood', wallMaterial: 'white', wallColor: '#f8f8f8', floorColor: '#c8a26b' },
        { id: 'r2', name: 'Virtuvė', type: 'kitchen', x: 5.5, y: 0, width: 3, height: 4, floorMaterial: 'tile', wallMaterial: 'cream', wallColor: '#f5f0e0', floorColor: '#e0d8c0' },
        { id: 'r3', name: 'Miegamasis', type: 'bedroom', x: 0, y: 4, width: 4, height: 3.5, floorMaterial: 'carpet', wallMaterial: 'blue', wallColor: '#c8d8e8', floorColor: '#b8a898' },
        { id: 'r4', name: 'Vonios kambarys', type: 'bathroom', x: 4, y: 4, width: 2.5, height: 2, floorMaterial: 'tile', wallMaterial: 'white', wallColor: '#f0f0f0', floorColor: '#e0e0e0' },
        { id: 'r5', name: 'Prieškambaris', type: 'hallway', x: 4, y: 6, width: 4.5, height: 1.5, floorMaterial: 'tile', wallMaterial: 'cream', wallColor: '#f5f0e0', floorColor: '#d0c8b0' },
      ],
      doors: [
        { id: 'd1', roomId: 'r1', wall: 'bottom', position: 0.5, width: 0.9, swingIn: false },
        { id: 'd2', roomId: 'r2', wall: 'bottom', position: 0.5, width: 0.9, swingIn: true },
        { id: 'd3', roomId: 'r3', wall: 'right', position: 0.5, width: 0.9, swingIn: true },
        { id: 'd4', roomId: 'r4', wall: 'bottom', position: 0.4, width: 0.7, swingIn: true },
      ],
      windows: [
        { id: 'w1', roomId: 'r1', wall: 'top', position: 0.35, width: 1.6, height: 1.4, sillHeight: 0.9 },
        { id: 'w2', roomId: 'r2', wall: 'top', position: 0.5, width: 1.2, height: 1.2, sillHeight: 0.9 },
        { id: 'w3', roomId: 'r2', wall: 'right', position: 0.5, width: 1.0, height: 1.0, sillHeight: 0.9 },
        { id: 'w4', roomId: 'r3', wall: 'left', position: 0.4, width: 1.4, height: 1.2, sillHeight: 0.9 },
        { id: 'w5', roomId: 'r3', wall: 'bottom', position: 0.5, width: 1.2, height: 1.2, sillHeight: 0.9 },
      ],
      furniture: [
        { id: 'f1', type: 'sofa', name: 'Sofa', x: 0.5, y: 2.0, width: 2.4, depth: 0.95, rotation: 0, color: '#5a7fa0' },
        { id: 'f2', type: 'coffee-table', name: 'Kavos staliukas', x: 1.0, y: 1.1, width: 1.2, depth: 0.6, rotation: 0, color: '#a07850' },
        { id: 'f3', type: 'tv-stand', name: 'TV spintelė', x: 3.0, y: 0.1, width: 1.8, depth: 0.45, rotation: 0, color: '#3a3a3a' },
        { id: 'f4', type: 'kitchen-counter', name: 'Virtuvinė', x: 5.6, y: 0.1, width: 2.8, depth: 0.6, rotation: 0, color: '#d8d8d8' },
        { id: 'f5', type: 'sink', name: 'Kriauklė', x: 7.8, y: 1.0, width: 0.6, depth: 0.5, rotation: 90, color: '#e8e8e8' },
        { id: 'f6', type: 'double-bed', name: 'Dvigulė lova', x: 0.3, y: 4.4, width: 1.8, depth: 2.1, rotation: 0, color: '#e0d0c0' },
        { id: 'f7', type: 'wardrobe', name: 'Spinta', x: 2.8, y: 4.1, width: 1.2, depth: 0.6, rotation: 0, color: '#c8b89a' },
        { id: 'f8', type: 'toilet', name: 'Tualetas', x: 4.1, y: 4.1, width: 0.5, depth: 0.7, rotation: 0, color: '#f0f0f0' },
        { id: 'f9', type: 'bathtub', name: 'Vonia', x: 4.8, y: 4.1, width: 0.75, depth: 1.65, rotation: 0, color: '#e8f0f8' },
      ],
    },
  },
  {
    name: '2 miegamųjų namas',
    description: '90 m² · 6 kambariai',
    icon: '🏡',
    plan: {
      name: '2 miegamųjų namas',
      wallHeight: 2.8,
      rooms: [
        { id: 'r1', name: 'Svetainė', type: 'living', x: 0, y: 0, width: 6, height: 5, floorMaterial: 'wood', wallMaterial: 'white', wallColor: '#f8f8f8', floorColor: '#c8a26b' },
        { id: 'r2', name: 'Virtuvė-Valgomasis', type: 'kitchen', x: 6, y: 0, width: 4, height: 5, floorMaterial: 'tile', wallMaterial: 'cream', wallColor: '#f5f0e0', floorColor: '#e0d8c0' },
        { id: 'r3', name: 'Miegamasis 1', type: 'bedroom', x: 0, y: 5, width: 4, height: 4, floorMaterial: 'carpet', wallMaterial: 'blue', wallColor: '#c8d8e8', floorColor: '#b8a898' },
        { id: 'r4', name: 'Miegamasis 2', type: 'bedroom', x: 6, y: 5, width: 4, height: 4, floorMaterial: 'carpet', wallMaterial: 'green', wallColor: '#c8e0c8', floorColor: '#b0c0a8' },
        { id: 'r5', name: 'Vonios kambarys', type: 'bathroom', x: 4, y: 5, width: 2, height: 2.5, floorMaterial: 'tile', wallMaterial: 'white', wallColor: '#f0f0f0', floorColor: '#e0e0e0' },
        { id: 'r6', name: 'Prieškambaris', type: 'hallway', x: 4, y: 7.5, width: 2, height: 1.5, floorMaterial: 'tile', wallMaterial: 'cream', wallColor: '#f5f0e0', floorColor: '#d0c8b0' },
      ],
      doors: [
        { id: 'd1', roomId: 'r1', wall: 'bottom', position: 0.4, width: 0.9, swingIn: false },
        { id: 'd2', roomId: 'r2', wall: 'bottom', position: 0.4, width: 0.9, swingIn: false },
        { id: 'd3', roomId: 'r3', wall: 'right', position: 0.4, width: 0.9, swingIn: true },
        { id: 'd4', roomId: 'r4', wall: 'left', position: 0.4, width: 0.9, swingIn: true },
        { id: 'd5', roomId: 'r5', wall: 'bottom', position: 0.4, width: 0.7, swingIn: true },
      ],
      windows: [
        { id: 'w1', roomId: 'r1', wall: 'top', position: 0.25, width: 1.6, height: 1.4, sillHeight: 0.9 },
        { id: 'w2', roomId: 'r1', wall: 'top', position: 0.7, width: 1.6, height: 1.4, sillHeight: 0.9 },
        { id: 'w3', roomId: 'r1', wall: 'left', position: 0.5, width: 1.2, height: 1.4, sillHeight: 0.9 },
        { id: 'w4', roomId: 'r2', wall: 'top', position: 0.5, width: 1.4, height: 1.2, sillHeight: 0.9 },
        { id: 'w5', roomId: 'r2', wall: 'right', position: 0.4, width: 1.2, height: 1.2, sillHeight: 0.9 },
        { id: 'w6', roomId: 'r3', wall: 'left', position: 0.4, width: 1.4, height: 1.2, sillHeight: 0.9 },
        { id: 'w7', roomId: 'r3', wall: 'bottom', position: 0.5, width: 1.2, height: 1.2, sillHeight: 0.9 },
        { id: 'w8', roomId: 'r4', wall: 'right', position: 0.4, width: 1.4, height: 1.2, sillHeight: 0.9 },
        { id: 'w9', roomId: 'r4', wall: 'bottom', position: 0.5, width: 1.2, height: 1.2, sillHeight: 0.9 },
      ],
      furniture: [
        { id: 'f1', type: 'sofa', name: 'Sofa', x: 0.5, y: 2.5, width: 2.8, depth: 0.95, rotation: 0, color: '#5a7fa0' },
        { id: 'f2', type: 'armchair', name: 'Fotelis', x: 4.0, y: 2.5, width: 0.85, depth: 0.85, rotation: 270, color: '#5a7fa0' },
        { id: 'f3', type: 'coffee-table', name: 'Kavos staliukas', x: 1.5, y: 1.5, width: 1.2, depth: 0.6, rotation: 0, color: '#a07850' },
        { id: 'f4', type: 'tv-stand', name: 'TV spintelė', x: 0.5, y: 0.1, width: 2.5, depth: 0.5, rotation: 0, color: '#2a2a2a' },
        { id: 'f5', type: 'dining-table', name: 'Valgomojo stalas', x: 6.5, y: 1.5, width: 2.0, depth: 1.0, rotation: 0, color: '#c8a26b' },
        { id: 'f6', type: 'kitchen-counter', name: 'Virtuvinė L', x: 6.1, y: 0.1, width: 3.8, depth: 0.6, rotation: 0, color: '#d8d8d8' },
        { id: 'f7', type: 'double-bed', name: 'Dvigulė lova', x: 0.3, y: 5.5, width: 1.8, depth: 2.1, rotation: 0, color: '#e0d0c0' },
        { id: 'f8', type: 'wardrobe', name: 'Spinta', x: 2.5, y: 5.1, width: 1.4, depth: 0.6, rotation: 0, color: '#c8b89a' },
        { id: 'f9', type: 'double-bed', name: 'Dvigulė lova', x: 6.3, y: 5.5, width: 1.8, depth: 2.1, rotation: 0, color: '#d8c8e0' },
        { id: 'f10', type: 'wardrobe', name: 'Spinta', x: 8.3, y: 5.1, width: 1.5, depth: 0.6, rotation: 0, color: '#c8b89a' },
        { id: 'f11', type: 'toilet', name: 'Tualetas', x: 4.1, y: 5.1, width: 0.5, depth: 0.7, rotation: 0, color: '#f0f0f0' },
        { id: 'f12', type: 'shower', name: 'Dušas', x: 4.1, y: 6.2, width: 0.9, depth: 0.9, rotation: 0, color: '#e8f0f8' },
        { id: 'f13', type: 'sink', name: 'Kriauklė', x: 5.2, y: 5.1, width: 0.6, depth: 0.45, rotation: 0, color: '#e8e8e8' },
        { id: 'f14', type: 'plant', name: 'Augalas', x: 5.2, y: 3.5, width: 0.4, depth: 0.4, rotation: 0, color: '#4a8a4a' },
      ],
    },
  },
  {
    name: 'Šeimos namas',
    description: '140 m² · 8 kambariai',
    icon: '🏘️',
    plan: {
      name: 'Šeimos namas',
      wallHeight: 2.9,
      rooms: [
        { id: 'r1', name: 'Svetainė', type: 'living', x: 0, y: 0, width: 6.5, height: 5.5, floorMaterial: 'wood', wallMaterial: 'white', wallColor: '#f8f8f8', floorColor: '#c8a26b' },
        { id: 'r2', name: 'Valgomasis', type: 'dining', x: 6.5, y: 0, width: 4, height: 3.5, floorMaterial: 'wood', wallMaterial: 'cream', wallColor: '#f5f0e0', floorColor: '#c8a26b' },
        { id: 'r3', name: 'Virtuvė', type: 'kitchen', x: 6.5, y: 3.5, width: 4, height: 3, floorMaterial: 'tile', wallMaterial: 'cream', wallColor: '#f5f0e0', floorColor: '#e0d8c0' },
        { id: 'r4', name: 'Prieškambaris', type: 'hallway', x: 0, y: 5.5, width: 3, height: 2.5, floorMaterial: 'tile', wallMaterial: 'white', wallColor: '#f0f0f0', floorColor: '#d0c8b0' },
        { id: 'r5', name: 'Vonios kamb. 1', type: 'bathroom', x: 3, y: 5.5, width: 3.5, height: 2.5, floorMaterial: 'tile', wallMaterial: 'white', wallColor: '#f0f0f0', floorColor: '#e0e0e0' },
        { id: 'r6', name: 'Miegamasis 1', type: 'bedroom', x: 0, y: 8, width: 4.5, height: 4, floorMaterial: 'carpet', wallMaterial: 'blue', wallColor: '#c8d8e8', floorColor: '#b8a898' },
        { id: 'r7', name: 'Miegamasis 2', type: 'bedroom', x: 4.5, y: 8, width: 3.5, height: 4, floorMaterial: 'carpet', wallMaterial: 'green', wallColor: '#c8e0c8', floorColor: '#b0c0a8' },
        { id: 'r8', name: 'Miegamasis 3', type: 'bedroom', x: 8, y: 8, width: 2.5, height: 4, floorMaterial: 'carpet', wallMaterial: 'cream', wallColor: '#f5ede0', floorColor: '#b8a898' },
        { id: 'r9', name: 'Vonios kamb. 2', type: 'bathroom', x: 8, y: 5.5, width: 2.5, height: 2.5, floorMaterial: 'tile', wallMaterial: 'white', wallColor: '#f0f0f0', floorColor: '#e0e0e0' },
        { id: 'r10', name: 'Koridorius', type: 'hallway', x: 6.5, y: 5.5, width: 1.5, height: 2.5, floorMaterial: 'tile', wallMaterial: 'cream', wallColor: '#f5f0e0', floorColor: '#d0c8b0' },
      ],
      doors: [
        { id: 'd1', roomId: 'r1', wall: 'right', position: 0.7, width: 0.9, swingIn: false },
        { id: 'd2', roomId: 'r3', wall: 'left', position: 0.5, width: 0.9, swingIn: true },
        { id: 'd3', roomId: 'r1', wall: 'bottom', position: 0.3, width: 0.9, swingIn: false },
        { id: 'd4', roomId: 'r5', wall: 'left', position: 0.4, width: 0.7, swingIn: true },
        { id: 'd5', roomId: 'r6', wall: 'top', position: 0.4, width: 0.9, swingIn: true },
        { id: 'd6', roomId: 'r7', wall: 'top', position: 0.5, width: 0.9, swingIn: true },
        { id: 'd7', roomId: 'r8', wall: 'top', position: 0.4, width: 0.9, swingIn: true },
        { id: 'd8', roomId: 'r9', wall: 'bottom', position: 0.4, width: 0.7, swingIn: true },
      ],
      windows: [
        { id: 'w1', roomId: 'r1', wall: 'top', position: 0.25, width: 1.8, height: 1.4, sillHeight: 0.9 },
        { id: 'w2', roomId: 'r1', wall: 'top', position: 0.65, width: 1.8, height: 1.4, sillHeight: 0.9 },
        { id: 'w3', roomId: 'r1', wall: 'left', position: 0.4, width: 1.4, height: 1.4, sillHeight: 0.9 },
        { id: 'w4', roomId: 'r2', wall: 'top', position: 0.5, width: 1.4, height: 1.2, sillHeight: 0.9 },
        { id: 'w5', roomId: 'r2', wall: 'right', position: 0.5, width: 1.2, height: 1.2, sillHeight: 0.9 },
        { id: 'w6', roomId: 'r3', wall: 'right', position: 0.5, width: 1.2, height: 1.2, sillHeight: 0.9 },
        { id: 'w7', roomId: 'r6', wall: 'left', position: 0.5, width: 1.4, height: 1.2, sillHeight: 0.9 },
        { id: 'w8', roomId: 'r6', wall: 'bottom', position: 0.4, width: 1.4, height: 1.2, sillHeight: 0.9 },
        { id: 'w9', roomId: 'r7', wall: 'bottom', position: 0.5, width: 1.2, height: 1.2, sillHeight: 0.9 },
        { id: 'w10', roomId: 'r8', wall: 'bottom', position: 0.5, width: 1.0, height: 1.2, sillHeight: 0.9 },
        { id: 'w11', roomId: 'r8', wall: 'right', position: 0.4, width: 1.0, height: 1.2, sillHeight: 0.9 },
      ],
      furniture: [
        { id: 'f1', type: 'sofa', name: 'Sofa', x: 0.5, y: 3.0, width: 2.8, depth: 1.0, rotation: 0, color: '#4a6a80' },
        { id: 'f2', type: 'armchair', name: 'Fotelis', x: 5.0, y: 3.2, width: 0.85, depth: 0.85, rotation: 270, color: '#4a6a80' },
        { id: 'f3', type: 'coffee-table', name: 'Staliukas', x: 1.5, y: 2.0, width: 1.4, depth: 0.7, rotation: 0, color: '#a07850' },
        { id: 'f4', type: 'tv-stand', name: 'TV', x: 0.5, y: 0.1, width: 3.0, depth: 0.5, rotation: 0, color: '#1a1a1a' },
        { id: 'f5', type: 'bookshelf', name: 'Knygų lentyna', x: 5.5, y: 0.1, width: 1.0, depth: 0.35, rotation: 0, color: '#6b4c11' },
        { id: 'f6', type: 'dining-table', name: 'Valgomasis stalas', x: 7.0, y: 0.5, width: 2.0, depth: 1.2, rotation: 0, color: '#c8a26b' },
        { id: 'f7', type: 'kitchen-counter', name: 'Virtuvinė', x: 6.6, y: 3.6, width: 3.8, depth: 0.6, rotation: 0, color: '#d0d0d0' },
        { id: 'f8', type: 'sink', name: 'Kriauklė', x: 9.8, y: 5.5, width: 0.6, depth: 0.5, rotation: 0, color: '#e8e8e8' },
        { id: 'f9', type: 'double-bed', name: 'Dvigulė lova', x: 0.3, y: 8.5, width: 2.0, depth: 2.1, rotation: 0, color: '#e0d0c0' },
        { id: 'f10', type: 'wardrobe', name: 'Spinta', x: 3.3, y: 8.1, width: 1.0, depth: 0.6, rotation: 0, color: '#c8b89a' },
        { id: 'f11', type: 'single-bed', name: 'Lova', x: 4.6, y: 8.5, width: 1.0, depth: 1.9, rotation: 0, color: '#d8e0f0' },
        { id: 'f12', type: 'desk', name: 'Rašomasis stalas', x: 5.8, y: 8.1, width: 1.2, depth: 0.6, rotation: 0, color: '#b8a0e0' },
        { id: 'f13', type: 'single-bed', name: 'Lova', x: 8.1, y: 8.5, width: 1.0, depth: 1.9, rotation: 0, color: '#f0e0d0' },
        { id: 'f14', type: 'toilet', name: 'Tualetas', x: 3.1, y: 5.6, width: 0.5, depth: 0.7, rotation: 0, color: '#f0f0f0' },
        { id: 'f15', type: 'bathtub', name: 'Vonia', x: 4.2, y: 5.6, width: 0.75, depth: 1.65, rotation: 0, color: '#e8f0f8' },
        { id: 'f16', type: 'toilet', name: 'Tualetas', x: 8.1, y: 5.6, width: 0.5, depth: 0.7, rotation: 0, color: '#f0f0f0' },
        { id: 'f17', type: 'shower', name: 'Dušas', x: 9.2, y: 5.6, width: 0.9, depth: 0.9, rotation: 0, color: '#e8f0f8' },
        { id: 'f18', type: 'plant', name: 'Augalas', x: 0.1, y: 0.1, width: 0.4, depth: 0.4, rotation: 0, color: '#3a7a3a' },
        { id: 'f19', type: 'plant', name: 'Augalas', x: 6.2, y: 7.0, width: 0.4, depth: 0.4, rotation: 0, color: '#3a7a3a' },
      ],
    },
  },
];
